version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=synthia

volumes:
  postgres-dev: