basePath: /patient/api
consumes:
- application/json
definitions:
  datastore.BloodPressure:
    properties:
      created_at:
        type: string
      date_time:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      diastolic:
        type: integer
      id:
        type: integer
      patient_id:
        type: integer
      pulse:
        type: integer
      systolic:
        type: integer
      updated_at:
        type: string
    type: object
  datastore.CreditCard:
    properties:
      brand:
        type: string
      created_at:
        type: string
      id:
        type: integer
      last_4_digits:
        type: string
      name:
        type: string
      patient_id:
        type: integer
      updated_at:
        type: string
    type: object
  datastore.Glucose:
    properties:
      created_at:
        type: string
      date_time:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      is_before_meal:
        type: boolean
      patient_id:
        type: integer
      updated_at:
        type: string
      value:
        type: integer
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  handler.AddCreditCardRequest:
    properties:
      card_token:
        type: string
      name:
        type: string
    required:
    - card_token
    - name
    type: object
  handler.BloodPressureRequest:
    properties:
      date_time:
        type: string
      diastolic:
        type: integer
      pulse:
        type: integer
      systolic:
        type: integer
    required:
    - date_time
    - diastolic
    - pulse
    - systolic
    type: object
  handler.GlucoseRequest:
    properties:
      date_time:
        type: string
      is_before_meal:
        type: boolean
      value:
        type: integer
    required:
    - date_time
    - is_before_meal
    - value
    type: object
  handler.PayInvoiceWithCreditCardResponse:
    properties:
      amount:
        type: number
      created_at:
        type: string
      credit_card:
        $ref: '#/definitions/datastore.CreditCard'
      creditCardID:
        type: integer
      failure_message:
        type: string
      id:
        type: integer
      invoice_id:
        type: integer
      method:
        type: string
      paid_at:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  handler.SigninRequest:
    properties:
      credential:
        type: string
    required:
    - credential
    type: object
  handler.SigninResponse:
    properties:
      phone_number:
        type: string
    type: object
  handler.VerifyOTPRequest:
    properties:
      otp:
        type: string
    required:
    - otp
    type: object
  handler.VerifyOTPResponse:
    properties:
      token:
        type: string
    type: object
  server.ErrorResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a Synthia patient backend API.
  title: Synthia Patient Backend API
  version: 1.0.0
paths:
  /auth/signin:
    post:
      description: Initiate auth process with government credential which will sent
        OTP to patient's phone number
      parameters:
      - description: Patient government credential (Passport ID or National ID)
        in: body
        name: SigninRequest
        required: true
        schema:
          $ref: '#/definitions/handler.SigninRequest'
      responses:
        "201":
          description: OTP is sent to patient's phone number
          schema:
            $ref: '#/definitions/handler.SigninResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: Provided credential is not in the hospital system
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Start signing-in with government credential
      tags:
      - Auth
  /auth/verify:
    post:
      description: Complete auth process with OTP verification. It will return token
        if verification success.
      parameters:
      - description: OTP that is sent to patient's phone number
        in: body
        name: VerifyOTPRequest
        required: true
        schema:
          $ref: '#/definitions/handler.VerifyOTPRequest'
      responses:
        "201":
          description: JWS Token for later use
          schema:
            $ref: '#/definitions/handler.VerifyOTPResponse'
        "400":
          description: OTP is invalid or expired
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      summary: Verify OTP and get token
      tags:
      - Auth
  /measurement/blood-pressure:
    post:
      parameters:
      - description: Blood pressure information
        in: body
        name: BloodPressureRequest
        required: true
        schema:
          $ref: '#/definitions/handler.BloodPressureRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/datastore.BloodPressure'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Record blood pressure
      tags:
      - Measurement
  /measurement/glucose:
    post:
      parameters:
      - description: Glucose level information
        in: body
        name: GlucoseRequest
        required: true
        schema:
          $ref: '#/definitions/handler.GlucoseRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/datastore.Glucose'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Record glucose level
      tags:
      - Measurement
  /payment/credit-card:
    get:
      responses:
        "200":
          description: List of saved cards
          schema:
            items:
              $ref: '#/definitions/datastore.CreditCard'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Get lists of saved credit cards
      tags:
      - Payment
    post:
      parameters:
      - description: Token from Omise and name of credit card
        in: body
        name: AddCreditCardRequest
        required: true
        schema:
          $ref: '#/definitions/handler.AddCreditCardRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Limited number of credit cards is reached
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Add new credit card
      tags:
      - Payment
  /payment/credit-card/{userID}:
    delete:
      parameters:
      - description: ID of the credit card to delete
        in: path
        name: cardID
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Invalid credit card ID
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: Patient doesn't own the specified credit card
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: Credit card not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Delete saved credit card
      tags:
      - Payment
  /payment/pay/{invoiceID}/credit-card/{cardID}:
    post:
      parameters:
      - description: ID of the credit card to be charged
        in: path
        name: cardID
        required: true
        type: integer
      - description: ID of the invoice to pay
        in: path
        name: invoiceID
        required: true
        type: integer
      responses:
        "201":
          description: Payment information
          schema:
            $ref: '#/definitions/handler.PayInvoiceWithCreditCardResponse'
        "400":
          description: Invalid credit card ID or invoice ID
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: Patient doesn't own the specified credit card or invoice
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: Credit card or invoice not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      security:
      - UserID: []
      - JWSToken: []
      summary: Pay invoice with credit card method
      tags:
      - Payment
produces:
- application/json
securityDefinitions:
  JWSToken:
    in: header
    name: Authorization
    type: apiKey
  UserID:
    in: header
    name: X-USER-ID
    type: apiKey
swagger: "2.0"
