name: Unit test

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches: 
      - 'main'
      - 'develop'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_DB: synthia
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@v1.6.0
    - name: Get Ginkgo
      run: go get github.com/onsi/ginkgo/v2/ginkgo
    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo
    - name: mockgen
      run: make mockgen
    - name: Run unit tests
      run: make unit-test
      env: 
        GIN_MODE: test
        OMISE_PUBLIC_KEY: ${{ secrets.OMISE_PUBLIC_KEY }}
        OMISE_SECRET_KEY: ${{ secrets.OMISE_SECRET_KEY }}
        HOSPITAL_SYS_ENDPOINT: "https://hospital-mock.synthia.tech/graphql"
